apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
    name: Auto-UI-Test    
spec:
    nodes:
        - advanced:
            qemu-append: -no-kvm
          general:
            hostname: Centos7a
            snapshot: true
          hardware:
            drives:
                - image: /phenix/images/centos7.qcow2
                  inject_partition: 3
            memory: 2048
            os_type: centos
          labels:
            ui-scripts: login-linux
          network:
            interfaces:
                - address: 192.168.1.2
                  gateway: 192.168.1.1
                  mask: 24
                  name: eth0
                  proto: static
                  type: ethernet
                  vlan: int_a
                - address: 192.168.2.4
                  gateway: 192.168.1.1
                  mask: 24
                  name: eth1
                  proto: static
                  type: ethernet
                  vlan: int_b
                - address: 192.168.3.3
                  gateway: 192.168.1.1
                  mask: 24
                  name: eth2
                  proto: static
                  type: ethernet
                  vlan: int_c
            routes:
                - cost: 1
                  destination: 192.168.80.5/24
                  next: 192.168.1.2
          type: VirtualMachine
        - advanced:
            qemu-append: -no-kvm
          general:
            hostname: Centos7b
            snapshot: true
          hardware:
            drives:
                - image: /phenix/images/centos7.qcow2
                  inject_partition: 3
            memory: 2048
            os_type: centos
          labels:
            ui-scripts: login-linux
          network:
            interfaces:
                - address: 192.168.1.5
                  gateway: 192.168.1.1
                  mask: 24
                  name: eth0
                  proto: static
                  type: ethernet
                  vlan: int_a
                - address: 192.168.2.6
                  gateway: 192.168.2.1
                  mask: 24
                  name: eth1
                  proto: static
                  type: ethernet
                  vlan: int_b
                - address: 192.168.3.7
                  gateway: 192.168.3.1
                  mask: 24
                  name: eth2
                  proto: static
                  type: ethernet
                  vlan: int_c
            routes:
                - cost: 1
                  destination: 192.168.80.5/24
                  next: 192.168.1.1
          type: VirtualMachine
        - advanced:
            qemu-append: -no-kvm
          general:
            hostname: WinXP
            snapshot: true
          hardware:
            drives:
                - image: /phenix/images/winxp_test.qcow2
                  inject_partition: 1
            memory: 2048
            os_type: windows
          labels:
            ui-scripts: windows-conf-network
          network:
            interfaces:
                - address: 192.168.5.3
                  gateway: 192.168.5.1
                  mac: 00:02:01:20:30:5f
                  mask: 24
                  name: eth0
                  proto: static
                  type: ethernet
                  vlan: int_a
                - address: 192.168.6.4
                  gateway: 192.168.6.1
                  mac: 00:02:01:20:30:5e
                  mask: 24
                  name: eth2
                  proto: static
                  type: ethernet
                  vlan: int_b
          overrides: []
          type: VirtualMachine
        - advanced:
            qemu-append: -no-kvm
          general:
            hostname: Win7
            snapshot: true
          hardware:
            drives:
                - image: /phenix/images/win7.qcow2
                  inject_partition: 1
            memory: 4096
            os_type: windows
          labels:
            ui-scripts: windows7-conf-network
          network:
            interfaces:
                - address: 192.168.10.3
                  gateway: 192.168.10.1
                  mac: 00:02:01:20:30:5a
                  mask: 24
                  name: eth0
                  proto: static
                  type: ethernet
                  vlan: int_z
                - address: 192.168.11.4
                  gateway: 192.168.10.1
                  mac: 00:02:01:20:30:5b
                  mask: 24
                  name: eth2
                  proto: static
                  type: ethernet
                  vlan: int_y
          overrides: []
          type: VirtualMachine
