apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
    name: SerialTest    
spec:
    nodes:
        - general:
            hostname: Serial1
            snapshot: true
          hardware:
            drives:
                - image: /phenix/images/lubuntu.qcow2
                  inject_partition: 1
            memory: 4096
            os_type: linux
          network:
            interfaces:
                - address: 192.168.1.2
                  gateway: 192.168.1.1
                  mask: 24
                  name: eth0
                  proto: static
                  type: ethernet
                  vlan: int_a                                              
          type: VirtualMachine
          overrides: []
          advanced: 
               qemu-append: "-serial tcp:192.168.40.1:4444,server,nowait"
        - general:
            hostname: Kali2022
            snapshot: true
          hardware:
            drives:
                - image: /phenix/images/kali2022.qcow2
                  inject_partition: 1
            memory: 4096
            os_type: linux
          network:
            interfaces:
                - address: 192.168.1.3
                  gateway: 192.168.1.1
                  mask: 24
                  name: eth0
                  proto: static
                  type: ethernet
                  vlan: int_a                                              
          type: VirtualMachine
          overrides: []
          advanced: 
               qemu-append: "-serial tcp:192.168.40.1:4444,server,nowait"

